### ISSUE TITLE
Standardise forms with label/description

### ISSUE THREAD

**Issue by yaili** [canonical-web-and-design/vanilla-store-theme-design#3]
From the Vanilla Store workshop: Standardise lists that are in the format "Label     Description": some have horizontal dividers, some have all text aligned left, some descriptions are aligned right

**Comment by kwm14** [comment]
### We've standardised Forms and there layout:

https://docs.vanillaframework.io/en/patterns/forms

So we now have different classes for your use case whether it be:

- Inline
- Stacked
- Group
- Validation

This update now resolves inconsistencies across products using forms so that all forms have a label with/without a description, text left aligned and form validation.
